#to use the below command lets 
#Install-WindowsFeature FS-SMBBW

Block-SmbShareAccess
Close-SmbOpenFile                                            
Close-SmbSession
Disable-SmbDelegation                                        
Enable-SmbDelegation
Get-SmbBandwidthLimit                                        
Get-SmbClientConfiguration                                                                     
Get-SmbConnection
Get-SmbDelegation 
Get-SmbClientNetworkInterface                                           
Get-SmbGlobalMapping                                                                                          
Get-SmbMultichannelConnection 
Get-SmbMapping
Get-SmbMultichannelConstraint                                
Get-SmbOpenFile                                                                                   
Get-SmbServerNetworkInterface
Get-SmbServerConfiguration                                                                                 
Get-SmbShare 
Get-SmbSession
Get-SmbShareAccess                                                                                             
Grant-SmbShareAccess                                                                                    
New-SmbMapping
New-SmbGlobalMapping                                                                                 
New-SmbShare         
New-SmbMultichannelConstraint
Remove-SmbBandwidthLimit                                     
Remove-SmbGlobalMapping 
Remove-SmbMapping                                            
Remove-SmbMultichannelConstraint                               
Remove-SmbShare                                              
Revoke-SmbShareAccess                                          
Set-SmbBandwidthLimit                                        
Set-SmbClientConfiguration                                     
Set-SmbPathAcl                                               
Set-SmbServerConfiguration                                     
Set-SmbShare                                                 
Unblock-SmbShareAccess                                         
Update-SmbMultichannelConnectio